title: REDCap (Research Data Capture) at Griffith
description: Documentation and self-directed learning for the REDCap instance at Griffith University.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/gu_logo.png"

# Aux links for the upper right navigation
aux_links:
  "GU Library Workshops":
    - "//griffithunilibrary.github.io"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Define callout colours and titles
callouts:
  warning:
    title: Warning
    color: red
  info:
    title: Info
    color: blue
  success:
    title: Success
    color: green
  error:
    title: More
    color: yellow
  highlight:
    title: Highlight
    color: grey-lt